#!/bin/bash -x
set -e

cd $(dirname $0)
pwd

mkdir -p out/

for TEST in tests/*; do
    TEST_NAME=$(echo ${TEST}|sed -E "s/tests\/(.*)_test.sv/\1/");
    if echo ${TEST} | grep _test >/dev/null; then
        echo "Compiling ${TEST}";
        rm -rf obj_dir;
        verilator --cc "${TEST}" -I.. -Itests/ --top-module test
        cd obj_dir
        g++ -DVL_USER_FINISH *.cpp *.h ../main.cpp /usr/share/verilator/include/verilated.cpp -I . -I /usr/share/verilator/include/ -O0 -g -lm -lstdc++ -o "../out/${TEST_NAME}.test"
        cd ..
        echo "Created out/$TEST_NAME.test";
    fi;
done;