#!/bin/bash

#rm -f obj_dir/* && verilator --cc  test_01.sv -I../common/  --top-module test_01 && ./make && ./sim
set -e

cd obj_dir
g++ -DVL_USER_FINISH *.cpp *.h ../main.cpp /usr/share/verilator/include/verilated.cpp -I . -I /usr/share/verilator/include/ -O0 -g -lm -lstdc++ -o ../sim
